# Este ficheiro deve ficar na RAIZ do seu projeto (junto ao build.gradle.kts)
# Ele diz ao motor do Qodana qual é a linguagem do nosso projeto.
version: "1.0"

# Linter gratuito para projetos Kotlin/Java
linter: jetbrains/qodana-jvm-community:latest

# Exclui a pasta de testes para ele focar apenas na qualidade do código de produção
exclude:
  - name: "src/test"